# -*- coding: utf-8 -*-
"""CrewAI Supply-Chain Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ySr2l7ruTT5V7kJVwyK_uTucexWZZw-n
"""

!pip install "crewai[litellm]" crewai-tools langchain-groq -q

print("[OK] Packages installed:")
print("  crewai[litellm] - CrewAI with Groq via LiteLLM")
print("  crewai-tools    - FileWriterTool, SerperDevTool, etc.")
print("  langchain-groq  - ChatGroq for LangGraph (used in Colab 2)")

# Cell 2 - Configure Groq API key
import os

# Option A: Colab Secrets (recommended)
# Add GROQ_API_KEY in the lock icon panel on the left sidebar
try:
    from google.colab import userdata
    os.environ["GROQ_API_KEY"] = userdata.get("groq_api_key")
    print("[OK] GROQ_API_KEY loaded from Colab Secrets")
except Exception:
    # Option B: paste directly (do not share the notebook with key visible)
    os.environ["GROQ_API_KEY"] = "gsk_..."  # <- replace with your key
    print("[WARN] Using hardcoded key - switch to Colab Secrets for production.")

key = os.environ.get("GROQ_API_KEY", "")
if key and key != "gsk_...":
    print(f"  Key prefix: {key[:8]}...")
else:
    print("[NO] GROQ_API_KEY not set - cells below will fail until you set it.")

# Cell 3 - Smoke test: single-agent hello world via Groq
from crewai import Agent, Task, Crew, Process

# In CrewAI v1, Groq models are referenced as 'groq/'
# LiteLLM handles the Groq API call under the hood.
GROQ_FAST    = "groq/llama-3.1-8b-instant"       # fast + cheap, good for simple tasks
GROQ_SMART   = "groq/llama-3.3-70b-versatile"    # capable, good for reasoning
GROQ_MANAGER = "groq/llama-3.3-70b-versatile"    # hierarchical manager LLM

test_agent = Agent(
    role="Hello World Agent",
    goal="Confirm the CrewAI + Groq environment is working correctly",
    backstory="A simple validation agent. You respond in exactly one sentence.",
    llm=GROQ_SMART,
    verbose=False,
    max_iter=2,
)

test_task = Task(
    description="Confirm you are running on Groq and identify your model in one sentence.",
    expected_output="One sentence confirming the environment works.",
    agent=test_agent,
)

test_crew = Crew(agents=[test_agent], tasks=[test_task], verbose=False)
result = test_crew.kickoff()

print("[OK] Smoke test PASSED - CrewAI + Groq is working")
print()
print(result.raw)

from crewai import Agent
from crewai_tools import FileWriterTool
from crewai.tools import BaseTool
from pydantic import Field

# LLM tiers
GROQ_FAST    = "groq/llama-3.1-8b-instant"
GROQ_SMART   = "groq/llama-3.3-70b-versatile"
GROQ_MANAGER = "groq/llama-3.3-70b-versatile"

file_writer = FileWriterTool()

# Mock search tool - no Serper API key required for this lab
# In production replace with: from crewai_tools import SerperDevTool
class MockSearchTool(BaseTool):
    name: str = "web_search"
    description: str = (
        "Search the web for supply-chain disruption news, "
        "shipping route data, and regulatory information."
    )

    def _run(self, query: str) -> str:
        return (
            f"[SIMULATED SEARCH] Results for: '{query}'\n"
            "Rotterdam: 18h closure, storm surge, severity 8/10\n"
            "Alternative 1 - Hamburg: +5h, -6% cost, low risk\n"
            "Alternative 2 - Felixstowe: +8h, -10% cost, medium risk\n"
            "Alternative 3 - Antwerp: +3h, +2% cost, low risk\n"
            "Singapore PSA: normal operations, no disruption\n"
        )

search_tool = MockSearchTool()

print("[OK] LLM tiers and tools configured")
print(f"  Fast model:    {GROQ_FAST}")
print(f"  Smart model:   {GROQ_SMART}")
print(f"  Manager model: {GROQ_MANAGER}")

# Cell 5 - Agent 1: Disruption Monitor
disruption_monitor = Agent(
    role="Supply Chain Disruption Monitor",
    goal=(
        "Continuously scan for logistics disruptions - port closures, weather events, "
        "customs delays, and supplier failures - and assess their severity on a 1-10 scale."
    ),
    backstory=(
        "You are a veteran logistics intelligence analyst with 12 years at Maersk and DHL. "
        "You have seen every kind of supply-chain disruption imaginable, from Suez Canal "
        "blockages to pandemic port shutdowns. You are calm under pressure, deeply data-driven, "
        "and always quantify impact before escalating. You write in crisp bullet points."
    ),
    llm=GROQ_SMART,
    tools=[search_tool],
    verbose=True,
    max_iter=4,
)

print("[OK] Agent 1:", disruption_monitor.role)

#added Agent 5
financial_analyst = Agent(
    role="Supply Chain Financial Analyst",
    goal=(
        "Calculate total EUR exposure: rerouting cost delta, "
        "SLA penalty clauses triggered, insurance deductible, "
        "and opportunity cost of delayed deliveries."
    ),
    backstory=(
        "CFA-qualified financial analyst specialising in logistics cost modelling. "
        "Always presents base case, worst case, and best case scenarios."
    ),
    llm=GROQ_SMART,
    verbose=True,
    max_iter=3,
)


# Cell 6 - Agent 2: Route Optimiser
route_optimiser = Agent(
    role="Logistics Route Optimiser",
    goal=(
        "Given a disruption report, calculate the 3 best alternative routes for affected "
        "shipments, ranking by total cost + estimated delay. Provide a clear recommendation."
    ),
    backstory=(
        "You are a PhD-level operations research specialist who spent 8 years building "
        "real-time routing algorithms for FedEx. You think in graphs, costs, and probabilities. "
        "You know every major shipping lane, air corridor, and rail route. You always present "
        "a primary recommendation plus two ranked alternatives with a weighted score."
    ),
    llm=GROQ_SMART,
    tools=[search_tool],
    verbose=True,
    max_iter=4,
)

print("[OK] Agent 2:", route_optimiser.role)

#added Agent 6
financial_analyst = Agent(
    role="Supply Chain Financial Analyst",
    goal=(
        "Calculate total EUR exposure: rerouting cost delta, "
        "SLA penalty clauses triggered, insurance deductible, "
        "and opportunity cost of delayed deliveries."
    ),
    backstory=(
        "CFA-qualified financial analyst specialising in logistics cost modelling. "
        "Always presents base case, worst case, and best case scenarios."
    ),
    llm=GROQ_SMART,
    verbose=True,
    max_iter=3,
)
print("[OK] Agent 6:", financial_analyst.role)

# Cell 6 - Agent 2: Route Optimiser
route_optimiser = Agent(
    role="Logistics Route Optimiser",
    goal=(
        "Given a disruption report, calculate the 3 best alternative routes for affected "
        "shipments, ranking by total cost + estimated delay. Provide a clear recommendation."
    ),
    backstory=(
        "You are a PhD-level operations research specialist who spent 8 years building "
        "real-time routing algorithms for FedEx. You think in graphs, costs, and probabilities. "
        "You know every major shipping lane, air corridor, and rail route. You always present "
        "a primary recommendation plus two ranked alternatives with a weighted score."
    ),
    llm=GROQ_SMART,
    tools=[search_tool],
    verbose=True,
    max_iter=4,
)

print("[OK] Agent 2:", route_optimiser.role)

# Cell 7 - Agent 3: Supplier Communications Specialist
supplier_comms = Agent(
    role="Supplier Communications Specialist",
    goal=(
        "Draft professional, urgent communications to affected suppliers and carriers "
        "explaining the disruption, proposing alternatives, and requesting confirmation "
        "within 4 hours."
    ),
    backstory=(
        "You are a senior procurement manager who has negotiated contracts in 22 countries. "
        "You are culturally fluent, direct but diplomatic, and always frame disruptions as "
        "collaborative problems to solve, never as blame assignments. You know that tone "
        "in a crisis email can make or break a supplier relationship worth millions."
    ),
    llm=GROQ_SMART,      # Drafting emails does not need the 70B model
    verbose=True,
    max_iter=3,
)

print("[OK] Agent 3:", supplier_comms.role)

# Cell 8 - Agent 4: Compliance Officer
compliance_officer = Agent(
    role="Trade Compliance Officer",
    goal=(
        "For each proposed re-route, verify customs requirements, check for sanctions or "
        "restricted-goods regulations, and flag any compliance risks. Issue a COMPLIANCE "
        "CLEARED or COMPLIANCE HOLD recommendation."
    ),
    backstory=(
        "You are a Certified Customs Specialist (CCS) with deep expertise in EU, US, and "
        "APAC trade regulations. You have worked with the WTO and have a zero-tolerance "
        "approach to compliance shortcuts. A single customs violation can cost more than "
        "the disruption itself."
    ),
    llm=GROQ_SMART,
    tools=[search_tool],
    verbose=True,
    max_iter=4,
)

print("[OK] Agent 4:", compliance_officer.role)

# Cell 9 - Agent 5: Executive Report Writer
report_writer = Agent(
    role="Executive Communications Writer",
    goal=(
        "Synthesise the disruption intelligence, route options, supplier actions, and "
        "compliance status into a clear, actionable executive briefing. "
        "Format: Situation -> Impact -> Response -> Next Steps. Maximum 1 page."
    ),
    backstory=(
        "You are a former management consultant who spent 10 years writing board-level "
        "crisis communications for Fortune 500 logistics companies. You eliminate jargon "
        "ruthlessly, lead with the bottom line, and always end with exactly 3 numbered "
        "action items with named owners and deadlines."
    ),
    llm=GROQ_SMART,
    tools=[file_writer],
    verbose=True,
    max_iter=3,
)

print("[OK] Agent 5:", report_writer.role)
print()
print("All 6 GlobalFlow agents ready.")

# Cell 10 - Task 1: Monitor disruptions
from crewai import Task

task_monitor = Task(
    description=(
        "Search for active logistics disruptions affecting GlobalFlow's key corridors: "
        "Rotterdam (EU hub), Singapore (APAC hub), Houston (US hub), and the AE-1 "
        "Asia-Europe shipping lane. Report: (1) disruption type and location, "
        "(2) severity score 1-10, (3) estimated duration, (4) shipments likely affected. "
        "Start your report with 'SEVERITY: X/10' on the first line."
    ),
    expected_output=(
        "Structured disruption report: severity score, affected corridors, "
        "shipment count, estimated duration, recommended escalation level."
    ),
    agent=disruption_monitor,
)

print("[OK] Task 1: Monitor disruptions  (no dependencies)")

#Extension task added
task_financial = Task(
    description="Calculate total EUR exposure: rerouting, SLA penalties, insurance.",
    expected_output="Financial exposure table: base / worst / best case in EUR.",
    agent=financial_analyst,
    context=[task_monitor, task_route],

)
print("[OK] Task 2:  financial_analyst    (context: task_route)")

# Cell 11 - Task 2: Route optimisation (depends on Task 1)
task_route = Task(
    description=(
        "Using the disruption report in your context, calculate 3 alternative routes "
        "for the 50 highest-priority shipments. For each route: "
        "(1) route name and via-points, (2) cost delta vs standard (%), "
        "(3) delay in hours, (4) risk score 1-5, (5) CO2 delta. "
        "Rank by weighted score: 60% cost, 30% time, 10% risk."
    ),
    expected_output=(
        "Ranked table of 3 alternative routes with cost delta, delay, risk, "
        "weighted score, and a one-sentence rationale for the top choice."
    ),
    agent=route_optimiser,
    context=[task_monitor],   # <- injects task_monitor output into this task
)

print("[OK] Task 2: Route optimisation   (context: task_monitor)")

# Cell 12 - Task 3: Supplier comms (depends on Tasks 1 + 2)
task_comms = Task(
    description=(
        "Draft communications to the 3 most critical affected suppliers. "
        "For each: (1) subject line, (2) 150-word email body explaining the disruption, "
        "the proposed re-routing option, and requesting confirmation within 4 hours. "
        "Tone: professional, urgent, collaborative."
    ),
    expected_output=(
        "Three complete email drafts formatted as:\n"
        "[SUPPLIER NAME] / [SUBJECT LINE]\n[EMAIL BODY]"
    ),
    agent=supplier_comms,
    context=[task_monitor, task_route],
)

print("[OK] Task 3: Supplier comms       (context: task_monitor, task_route)")

# Cell 13 - Task 4: Compliance check (depends on Task 2)
task_compliance = Task(
    description=(
        "Review the top-ranked re-routing option from the route optimisation team. "
        "Check: (1) customs requirements per transit country, "
        "(2) sanctions or dual-use goods restrictions, "
        "(3) certificate of origin implications. "
        "Issue COMPLIANCE CLEARED or COMPLIANCE HOLD with detailed reasoning."
    ),
    expected_output=(
        "Compliance status (CLEARED or HOLD), per-country requirements, "
        "flags with remediation steps, estimated customs processing time."
    ),
    agent=compliance_officer,
    context=[task_route],
)

print("[OK] Task 4: Compliance check     (context: task_route)")

# Cell 14 - Task 5: Executive report (all context)
task_report = Task(
    description=(
        "Compile all outputs into a single executive briefing.\n"
        "Use these exact headings:\n"
        "  SITUATION: what happened and severity\n"
        "  IMPACT: shipments affected, EUR cost exposure\n"
        "  RESPONSE: chosen re-route, supplier actions, compliance status\n"
        "  NEXT STEPS: exactly 3 numbered actions with owners and deadlines\n"
        "Maximum 400 words. Save to file 'globalflow_disruption_report.txt'."
    ),
    expected_output=(
        "Complete executive briefing saved to 'globalflow_disruption_report.txt', "
        "4-section structure, maximum 400 words."
    ),
    agent=report_writer,
    context=[task_monitor, task_route, task_comms, task_compliance],
    output_file="globalflow_disruption_report.txt",
)

print("[OK] Task 5: Executive report     (context: ALL tasks)")
print()
print("Task dependency chain:")
print("  task_monitor")
print("    +-> task_route ---------> task_compliance")
print("    +-> task_route ---+")
print("    +------------------+-> task_comms")
print("  ALL -----------------> task_report -> file output")

# Cell 15 - Assemble the Crew
from crewai import Crew, Process

globalflow_crew = Crew(
    agents=[
        disruption_monitor,
        route_optimiser,
        supplier_comms,
        compliance_officer,
        report_writer,
    ],
    tasks=[
        task_monitor,
        task_route,
        task_comms,
        task_compliance,
        task_report,
    ],
    process=Process.hierarchical,
    manager_llm=GROQ_MANAGER,   # Groq 70B orchestrates delegation
    verbose=True,
    memory=True,                # Enables long-term + short-term memory
    output_log_file="crew_run.log",
)
print("[OK] GlobalFlow Crew assembled")
print(f"  Agents:      {len(globalflow_crew.agents)}")
print(f"  Tasks:       {len(globalflow_crew.tasks)}")
print(f"  Process:     {globalflow_crew.process.value}")
print(f"  Manager LLM: {GROQ_MANAGER}")
print(f"  Memory:      {globalflow_crew.memory}")

# Cell 16 - Trigger: simulate a Rotterdam port closure
trigger_input = {
    "disruption_alert": (
        "ALERT: Port of Rotterdam (GlobalFlow EU hub) has declared force majeure "
        "due to severe North Sea storm surge. Expected closure: 18-24 hours. "
        "340 containers from GlobalFlow clients are currently docked. "
        "12 Maersk vessels en-route have been diverted to Felixstowe. "
        "Incident started: 2025-06-18 06:30 UTC. "
        "Client SLA breach window opens in 6 hours."
    )
}

print("[ALERT] TRIGGERING GlobalFlow Disruption Response Crew")
print("=" * 60)
print(trigger_input["disruption_alert"])
print("=" * 60)
print()
print("Starting crew kickoff - expect 2-5 minutes on Groq free tier.")
print("Watch each agent Thought -> Action -> Observation loop below.")
print()
result = globalflow_crew.kickoff(inputs=trigger_input)

# Review the final output (moved from Cell 17)
print("\n" + "=" * 60)
print("FINAL EXECUTIVE BRIEFING")
print("=" * 60)
print(result.raw)
print()
print("-" * 60)
print(f"Token usage: {result.token_usage}")

#Review the final output (moved from Cell 17)
print("\n" + "=" * 60)
print("FINAL EXECUTIVE BRIEFING")
print("=" * 60)
print(result.raw)
print()
print("-" * 60)
print(f"Token usage: {result.token_usage}")