# -*- coding: utf-8 -*-
"""Reseacrher_Supervisor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yLkoAGEwtfkjuwW9LEjP9Fa-hehGHUX-
"""

!pip install -q -U Langgraph langchain-groq tavily-python langchain_community

import os
from google.colab import userdata
os.environ['GROQ_API_KEY'] = userdata.get('groq_api_key')
os.environ['TAVILY_API_KEY'] = userdata.get('TAVILY_API_KEY')

import operator
from typing import Annotated, List, TypedDict, Literal
from pydantic import BaseModel, Field

# The State object that travels through the graph
class AgentState(TypedDict):
    task: str
    research_notes: Annotated[List[str], operator.add]
    draft: str
    next_node: str
    retry_count: int
    revision_feedback: str

# Schema for the Supervisor to follow
class Router(BaseModel):
    """Decide which worker to call next."""
    next_worker: Literal["researcher", "writer", "FINISH"] = Field(description="The next node to act")
    instructions: str = Field(description="Specific instructions for the worker")
    is_critical: bool = Field(description="If True, system will pause for human review")

from langchain_groq import ChatGroq
from langchain_community.tools.tavily_search import TavilySearchResults

# Using Llama 3.3 70B for the "Brain" (Supervisor)
llm = ChatGroq(model_name="llama-3.3-70b-versatile", temperature=0)
search_tool = TavilySearchResults(k=2)

def researcher(state: AgentState):
    print("🚀 Researcher is digging...")
    query = state['task']
    results = search_tool.invoke(query)
    print(results)
    return {"research_notes": [str(results)], "retry_count": 0}

def writer(state: AgentState):
    print("✍️ Writer is composing...")
    context = "\n".join(state['research_notes'])
    res = llm.invoke(f"Write a report on {state['task']} using: {context}")
    return {"draft": res.content}

def supervisor(state: AgentState):
    print("🧠 Supervisor is reviewing state...")
    # Groq supports structured output natively
    structured_llm = llm.with_structured_output(Router)

    prompt = f"""
    Task: {state['task']}
    Notes collected: {len(state['research_notes'])}
    Current Draft: {state['draft'][:100]}...
    If you have something in research_notes, select writer
    """
    print(f"Supervisor sees {len(state['research_notes'])} notes and draft length {len(state['draft'])}")
    decision = structured_llm.invoke(prompt)
    return {
        "next_node": decision.next_worker,
        "revision_feedback": decision.instructions
    }

# Graph with recovery and breakpoints
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver

builder = StateGraph(AgentState)

# Add nodes
builder.add_node("supervisor", supervisor)
builder.add_node("researcher", researcher)
builder.add_node("writer", writer)

# Logic
builder.set_entry_point("supervisor")

builder.add_conditional_edges(
    "supervisor",
    lambda x: x["next_node"],
    {"researcher": "researcher", "writer": "writer", "FINISH": END}
)

builder.add_edge("researcher", "supervisor")
builder.add_edge("writer", "supervisor")

# Enable Persistence (Recovery) and Breakpoints (Pause)
memory = MemorySaver()
graph = builder.compile(
    checkpointer=memory,
    interrupt_before=["writer"] # PAUSE: Allows human to review research before writing starts
)

config = {"configurable": {"thread_id": "workshop_user_1"}}
initial_input = {"task": "Impact of LPU architecture on AI inference speeds", "research_notes": [], "retry_count": 0, "draft": ""}

# 1. Start execution
print("--- STARTING GRAPH ---")
for event in graph.stream(initial_input, config, stream_mode="values"):
    if "next_node" in event:
        print(f"Moving to: {event['next_node']}")

# 2. Check if we hit a breakpoint (Pause)
snapshot = graph.get_state(config)
if snapshot.next:
    print(f"\n⏸️ SYSTEM PAUSED. Next step is: {snapshot.next}")
    print(f"Feedback from Supervisor: {snapshot.values['revision_feedback']}")

    # 3. Resume (Human says 'Go ahead')
    print("\n--- RESUMING AFTER PAUSE ---")
    #for event in graph.stream(None, config, stream_mode="values"):
    #    print("Finalizing...")

print("--- RESUMING GRAPH ---\n")
for event in graph.stream(None, config, stream_mode="values"):
    if "next_node" in event:
        print(f"Moving to: {event['next_node']}")
    elif "draft" in event:
        print(f"\n--- FINAL DRAFT ---:\n{event['draft']}")

!pip install graphviz

from graphviz import Digraph
from IPython.display import display, Image

dot = Digraph(
    "Multi Agent Research System",
    format="png"
)

# Nodes
dot.node("START", "START")

dot.node(
    "SUP",
    "Supervisor Agent\n(Router)\nStructured Output"
)

dot.node(
    "SEARCH",
    "Search Agent\n(Web Search)"
)

dot.node(
    "READ",
    "Read Agent\n(PDF / Docs\nExtraction)"
)

dot.node(
    "RAG",
    "RAG Agent\nChunking\nEmbedding\nVector DB"
)

dot.node(
    "WRITE",
    "Writer Agent\nReport Generation"
)

dot.node(
    "EVAL",
    "Evaluator Agent\nRAGAS\nGuardrails"
)

dot.node("END", "END")


# Flow
dot.edge("START", "SUP")

# Supervisor decisions
dot.edge(
    "SUP",
    "SEARCH",
    label="Need external info"
)

dot.edge(
    "SUP",
    "READ",
    label="Need document reading"
)

dot.edge(
    "SUP",
    "RAG",
    label="Need retrieval"
)


# Return to supervisor
dot.edge(
    "SEARCH",
    "SUP",
    label="research notes"
)

dot.edge(
    "READ",
    "SUP",
    label="extracted content"
)

dot.edge(
    "RAG",
    "SUP",
    label="context"
)


# Writing pipeline
dot.edge(
    "SUP",
    "WRITE",
    label="Enough context"
)

dot.edge(
    "WRITE",
    "EVAL",
    label="draft"
)

dot.edge(
    "EVAL",
    "SUP",
    label="feedback"
)

dot.edge(
    "SUP",
    "END",
    label="approved"
)


display(Image(dot.render()))