# -*- coding: utf-8 -*-
"""youtube_emotion_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K2Kdc-Pe4Eprlnw7OtKalS0GD0XxqkuI
"""

!pip install -q yt-dlp hume pandas plotly requests

"""## Step 2 — Set your API key and YouTube URL"""

# ── CONFIG — edit these two lines only ────────────────────────────
HUME_API_KEY  = ""   # paste your Hume.ai key
YOUTUBE_URL   = "https://www.youtube.com/shorts/FUfwzN5tnSI?feature=share"  # any YT URL or Short
# ──────────────────────────────────────────────────────────────────

# Models to run (choose any combination)
MODELS = ["face", "prosody", "language"]   # face=facial, prosody=voice, language=text

print("Config ready ✓")

"""## Step 3 — Download the YouTube video"""

import yt_dlp, os, glob

OUTPUT_DIR = "/content/video"
os.makedirs(OUTPUT_DIR, exist_ok=True)

ydl_opts = {
    "outtmpl":  f"{OUTPUT_DIR}/video.%(ext)s",
    "format":   "mp4/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best",
    "quiet":    False,
    "noplaylist": True,
}

print(f"Downloading: {YOUTUBE_URL}")
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    info = ydl.extract_info(YOUTUBE_URL, download=True)
    VIDEO_TITLE = info.get("title", "Unknown")

# Find the downloaded file
files = glob.glob(f"{OUTPUT_DIR}/video.*")
VIDEO_PATH = files[0] if files else None

if VIDEO_PATH:
    size_mb = os.path.getsize(VIDEO_PATH) / 1024 / 1024
    print(f"\n✅ Downloaded: {VIDEO_TITLE}")
    print(f"   File: {VIDEO_PATH}")
    print(f"   Size: {size_mb:.1f} MB")
else:
    print("❌ Download failed — check the URL")

"""## Step 4 — Submit to Hume.ai for emotion analysis"""

import requests, json, time

HUME_API_BASE = "https://api.hume.ai/v0/batch"

def submit_job(api_key, video_path, models):
    """Upload video and start a Hume.ai batch job."""
    headers = {"X-Hume-Api-Key": api_key}

    # Build model config
    model_config = {}
    for m in models:
        model_config[m] = {}

    files   = {"file":   open(video_path, "rb")}
    payload = {"json":   json.dumps({"models": model_config})}

    print(f"Submitting to Hume.ai — models: {models}")
    resp = requests.post(f"{HUME_API_BASE}/jobs",
                         headers=headers,
                         data=payload,
                         files=files)
    resp.raise_for_status()
    job_id = resp.json()["job_id"]
    print(f"✅ Job submitted — ID: {job_id}")
    return job_id


def wait_for_job(api_key, job_id, poll_interval=5):
    """Poll until the job completes."""
    headers = {"X-Hume-Api-Key": api_key}
    url     = f"{HUME_API_BASE}/jobs/{job_id}"

    print("\nWaiting for analysis to complete...")
    while True:
        resp   = requests.get(url, headers=headers)
        resp.raise_for_status()
        data   = resp.json()
        status = data.get("state", {}).get("status", "unknown")

        print(f"  Status: {status}", end="\r")

        if status == "COMPLETED":
            print(f"\n✅ Analysis complete!")
            return data
        elif status in ("FAILED", "CANCELLED"):
            print(f"\n❌ Job {status}")
            print(json.dumps(data, indent=2))
            return None

        time.sleep(poll_interval)


def fetch_predictions(api_key, job_id):
    """Fetch the full predictions for a completed job."""
    headers = {"X-Hume-Api-Key": api_key}
    url     = f"{HUME_API_BASE}/jobs/{job_id}/predictions"
    resp    = requests.get(url, headers=headers)
    resp.raise_for_status()
    return resp.json()


# Run the pipeline
job_id      = submit_job(HUME_API_KEY, VIDEO_PATH, MODELS)
job_status  = wait_for_job(HUME_API_KEY, job_id)

if job_status:
    predictions = fetch_predictions(HUME_API_KEY, job_id)
    print(f"\nFetched {len(predictions)} prediction record(s)")

"""## Step 5 — Parse results into DataFrames"""

import pandas as pd

def parse_face_emotions(predictions):
    rows = []
    for pred in predictions:
        results = pred.get("results", {}).get("predictions", [])
        for file_pred in results:
            for model_pred in file_pred.get("models", {}).get("face", {}).get("grouped_predictions", []):
                face_id = model_pred.get("id", "face_0")
                for frame in model_pred.get("predictions", []):
                    t = frame.get("time", 0)
                    for emotion in frame.get("emotions", []):
                        rows.append({
                            "time":    round(t, 3),
                            "face_id": face_id,
                            "emotion": emotion["name"],
                            "score":   round(emotion["score"], 4),
                        })
    return pd.DataFrame(rows)


def parse_prosody_emotions(predictions):
    rows = []
    for pred in predictions:
        results = pred.get("results", {}).get("predictions", [])
        for file_pred in results:
            for segment in file_pred.get("models", {}).get("prosody", {}).get("grouped_predictions", []):
                for chunk in segment.get("predictions", []):
                    t_start = chunk.get("time", {}).get("begin", 0)
                    t_end   = chunk.get("time", {}).get("end",   0)
                    for emotion in chunk.get("emotions", []):
                        rows.append({
                            "time_start": round(t_start, 3),
                            "time_end":   round(t_end,   3),
                            "emotion":    emotion["name"],
                            "score":      round(emotion["score"], 4),
                        })
    return pd.DataFrame(rows)


def parse_language_emotions(predictions):
    rows = []
    for pred in predictions:
        results = pred.get("results", {}).get("predictions", [])
        for file_pred in results:
            for segment in file_pred.get("models", {}).get("language", {}).get("grouped_predictions", []):
                for chunk in segment.get("predictions", []):
                    text = chunk.get("text", "")
                    t    = chunk.get("position", {}).get("begin", 0)
                    for emotion in chunk.get("emotions", []):
                        rows.append({
                            "time":    round(t, 3),
                            "text":    text,
                            "emotion": emotion["name"],
                            "score":   round(emotion["score"], 4),
                        })
    return pd.DataFrame(rows)


# Parse all models
df_face     = parse_face_emotions(predictions)
df_prosody  = parse_prosody_emotions(predictions)
df_language = parse_language_emotions(predictions)

print(f"Face rows:     {len(df_face)}")
print(f"Prosody rows:  {len(df_prosody)}")
print(f"Language rows: {len(df_language)}")

"""## Step 6 — Top emotions summary"""

def top_emotions(df, model_name, n=10):
    if df.empty:
        print(f"{model_name}: no data")
        return
    summary = (
        df.groupby("emotion")["score"]
        .mean()
        .sort_values(ascending=False)
        .head(n)
        .reset_index()
    )
    summary.columns = ["Emotion", "Avg Score"]
    summary["Avg Score"] = summary["Avg Score"].round(4)
    print(f"\n{'='*35}")
    print(f"  Top {n} — {model_name}")
    print(f"{'='*35}")
    print(summary.to_string(index=False))

top_emotions(df_face,     "Facial Expression")
top_emotions(df_prosody,  "Voice / Prosody")
top_emotions(df_language, "Language / Text")

"""## Step 7 — Visualise: top emotions bar chart"""

import plotly.graph_objects as go
from plotly.subplots import make_subplots

def make_bar_chart(df, title, color):
    if df.empty:
        return None
    top = df.groupby("emotion")["score"].mean().sort_values(ascending=False).head(12)
    return go.Bar(x=top.index.tolist(), y=top.values.tolist(),
                  name=title, marker_color=color, text=[f"{v:.3f}" for v in top.values],
                  textposition="outside")

specs    = [[{"type": "bar"}]] * 3
subtitles = ["Facial Expression", "Voice / Prosody", "Language / Text"]
fig = make_subplots(rows=3, cols=1, subplot_titles=subtitles, vertical_spacing=0.1)

for i, (df, title, color) in enumerate([
    (df_face,     "Face",     "#7c3aed"),
    (df_prosody,  "Prosody",  "#0f766e"),
    (df_language, "Language", "#b45309"),
], 1):
    trace = make_bar_chart(df, title, color)
    if trace:
        fig.add_trace(trace, row=i, col=1)

fig.update_layout(
    title_text=f"Emotion Analysis — {VIDEO_TITLE}",
    height=800, showlegend=False,
    template="plotly_white",
    font=dict(family="Arial", size=12),
)
fig.show()

"""## Step 8 — Emotion timeline (face over time)"""

import plotly.express as px

if not df_face.empty:
    # Pick top 5 emotions by average score
    top5 = df_face.groupby("emotion")["score"].mean().sort_values(ascending=False).head(5).index.tolist()
    df_top = df_face[df_face["emotion"].isin(top5)]

    fig = px.line(
        df_top, x="time", y="score", color="emotion",
        title="Facial Emotion Over Time — Top 5",
        labels={"time": "Time (seconds)", "score": "Emotion Score"},
        template="plotly_white",
    )
    fig.update_layout(height=400)
    fig.show()
else:
    print("No face data to plot")

"""## Step 9 — Heatmap: all emotions at a glance"""

import plotly.express as px

if not df_face.empty:
    # Pivot: rows = emotions, cols = time buckets
    df_face["time_bucket"] = (df_face["time"] // 1).astype(int)  # 1-second buckets
    pivot = df_face.groupby(["emotion", "time_bucket"])["score"].mean().unstack(fill_value=0)

    # Keep top 20 emotions by avg score
    top20 = df_face.groupby("emotion")["score"].mean().sort_values(ascending=False).head(20).index
    pivot = pivot.loc[pivot.index.isin(top20)]

    fig = px.imshow(
        pivot,
        labels=dict(x="Time (sec)", y="Emotion", color="Score"),
        title="Facial Emotion Heatmap",
        color_continuous_scale="Viridis",
        aspect="auto",
        template="plotly_white",
    )
    fig.update_layout(height=500)
    fig.show()
else:
    print("No face data for heatmap")

"""## Step 10 — Dominant emotion per second"""

if not df_face.empty:
    df_face["time_sec"] = (df_face["time"] // 1).astype(int)
    dominant = (
        df_face.loc[df_face.groupby("time_sec")["score"].idxmax()]
        [["time_sec", "emotion", "score"]]
        .sort_values("time_sec")
        .reset_index(drop=True)
    )
    dominant.columns = ["Second", "Dominant Emotion", "Score"]
    dominant["Score"] = dominant["Score"].round(4)
    print("\nDominant facial emotion per second:")
    print(dominant.to_string(index=False))

    # Most common overall dominant emotion
    most_common = dominant["Dominant Emotion"].value_counts().idxmax()
    print(f"\n🏆 Most dominant emotion in video: {most_common}")
else:
    print("No face data")

"""## Step 11 — Save results to CSV"""

from google.colab import files

# Save each model's data
outputs = {
    "face_emotions.csv":     df_face,
    "prosody_emotions.csv":  df_prosody,
    "language_emotions.csv": df_language,
}

for fname, df in outputs.items():
    if not df.empty:
        df.to_csv(fname, index=False)
        print(f"Saved: {fname} ({len(df)} rows)")
        files.download(fname)
    else:
        print(f"Skipped: {fname} (no data)")

"""## Step 12 — (Optional) Raw predictions JSON"""

# Uncomment to see raw JSON
# import json
# print(json.dumps(predictions, indent=2))