# -*- coding: utf-8 -*-
"""PromptTask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNzVj06Q7A8upn4M6r3X6l4oBfbpp57m
"""

!pip install -q langchain langchain-core langchain-groq

from getpass import getpass

groq_api_key = getpass("Enter your Groq API Key: ")

from langchain_core.prompts import PromptTemplate
from langchain_groq import ChatGroq

# LLM
llm = ChatGroq(
    groq_api_key=groq_api_key,
    model_name="llama-3.3-70b-versatile"
)

# Prompt
zero_shot_summary_prompt = PromptTemplate(
    input_variables=["earnings_text"],
    template="""
Summarize the following earnings call snippet.

Requirements:
- Maximum 3 bullet points
- Mention revenue trend
- Mention profitability
- Mention future outlook

Text:
{earnings_text}
"""
)

# Sample text
earnings_text = """
Revenue increased 18% year-over-year driven by strong cloud adoption.
Net profit margin improved from 12% to 16%.
Management expects continued growth next quarter and plans to expand AI offerings.
"""

# Create prompt
formatted_prompt = zero_shot_summary_prompt.format(
    earnings_text=earnings_text
)

# Invoke model
response = llm.invoke(formatted_prompt)

print(response.content)

from getpass import getpass
from langchain_core.prompts import PromptTemplate
from langchain_groq import ChatGroq

# Enter Groq API Key
groq_api_key = getpass("Enter Groq API Key: ")

# Initialize LLM
llm = ChatGroq(
    groq_api_key=groq_api_key,
    model_name="llama-3.3-70b-versatile"
)

# Few-Shot Prompt
few_shot_summary_prompt = PromptTemplate(
    input_variables=["earnings_text"],
    template="""
Example 1

Input:
Revenue increased 15% YoY. Net income rose 10%.
Management expects strong demand next quarter.

Output:
• Revenue grew 15%
• Profitability improved
• Positive future outlook

Example 2

Input:
Revenue declined 5%. Operating costs increased.
Management announced restructuring plans.

Output:
• Revenue decreased
• Costs increased
• Restructuring planned

Now summarize:

Input:
{earnings_text}

Output:
"""
)

# Test Data
earnings_text = """
Revenue increased 22% year-over-year driven by cloud services.
Net profit margin improved from 14% to 19%.
Management expects continued growth and expansion into new markets.
"""

# Format Prompt
prompt = few_shot_summary_prompt.format(
    earnings_text=earnings_text
)

# Generate Response
response = llm.invoke(prompt)

print(response.content)

from getpass import getpass
from langchain_core.prompts import PromptTemplate
from langchain_groq import ChatGroq

# Enter Groq API Key
groq_api_key = getpass("Enter Groq API Key: ")

# Initialize LLM
llm = ChatGroq(
    groq_api_key=groq_api_key,
    model_name="llama-3.3-70b-versatile"
)

# Prompt
ticket_classifier_prompt = PromptTemplate(
    input_variables=["ticket"],
    template="""
You are a customer support classifier.

Possible Classes:

1. Billing
2. Tech
3. Refund
4. General
5. Escalate

Think step-by-step:

Step 1: Identify customer issue
Step 2: Determine customer intent
Step 3: Select most appropriate class

Ticket:
{ticket}

Return:

Reasoning:
Class:
"""
)

# Sample ticket
ticket = """
I was charged twice for my subscription this month.
Please reverse the extra charge immediately.
"""

# Format prompt
prompt = ticket_classifier_prompt.format(ticket=ticket)

# Invoke model
response = llm.invoke(prompt)

print(response.content)

from getpass import getpass
from langchain_core.prompts import PromptTemplate
from langchain_groq import ChatGroq

# Enter Groq API Key
groq_api_key = getpass("Enter Groq API Key: ")

# Initialize Model
llm = ChatGroq(
    groq_api_key=groq_api_key,
    model_name="llama-3.3-70b-versatile"
)

# Prompt
generate_snippet_prompt = PromptTemplate(
    input_variables=["company", "quarter"],
    template="""
You are a financial analyst.

Generate a realistic earnings call snippet for {company} for {quarter}.

Include:
- Revenue growth or decline
- Profitability metrics
- Future guidance
- Market conditions

Return 100-150 words.
"""
)

# Create Prompt
prompt = generate_snippet_prompt.format(
    company="NexaBank",
    quarter="Q2 2026"
)

# Generate Response
response = llm.invoke(prompt)

print(response.content)

!pip install -q rouge-score

from rouge_score import rouge_scorer

reference_summary = (
    "Revenue increased and management provided positive guidance."
)

generated_summary = (
    "Revenue grew and outlook remains positive."
)

scorer = rouge_scorer.RougeScorer(
    ['rougeL'],
    use_stemmer=True
)

score = scorer.score(
    reference_summary,
    generated_summary
)

print("ROUGE-L Precision:",
      score['rougeL'].precision)

print("ROUGE-L Recall:",
      score['rougeL'].recall)

print("ROUGE-L F1:",
      score['rougeL'].fmeasure)