# -*- coding: utf-8 -*-
"""Financial_RAG_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZKYbqleWyhihYqcbgBm4WgKzk3IzilT6
"""

!pip install -q langchain langchain-community langchain-openai \
    faiss-cpu sentence-transformers openai \
    ragas datasets pypdf tiktoken \
    python-dotenv tqdm rich langchain-text-splitters \
    langchain-google-vertexai
print('✅ Dependencies installed')

!pip install -q langchain-openai
print('✅ `langchain-openai` installed')

!pip install -q langchain-core
print('✅ `langchain-core` installed')

!pip install -q langchain-text-splitters
print('✅ `langchain-text-splitters` installed')

import os
from google.colab import userdata

# --- Azure OpenAI Configuration ---
# Set these in Colab Secrets: AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_KEY, AZURE_OPENAI_DEPLOYMENT
AZURE_ENDPOINT   = userdata.get('AZURE_OPENAI_ENDPOINT')   # e.g. https://myresource.openai.azure.com/
AZURE_API_KEY    = userdata.get('AZURE_OPENAI_KEY')
AZURE_DEPLOYMENT = userdata.get('AZURE_OPENAI_DEPLOYMENT')  # e.g. 'gpt-4o'
AZURE_API_VERSION = '2024-06-01'

# --- HuggingFace Token (for private models / higher rate limits) ---
#HF_TOKEN = userdata.get('HF_TOKEN')  # optional for public models

print('✅ Credentials loaded' if AZURE_API_KEY else '❌ Missing Azure credentials — check Secrets')

import os
from google.colab import userdata

# --- Azure OpenAI Configuration ---
# Set these in Colab Secrets: AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_KEY, AZURE_OPENAI_DEPLOYMENT
AZURE_ENDPOINT   = userdata.get('AZURE_OPENAI_ENDPOINT')   # e.g. https://myresource.openai.azure.com/
AZURE_API_KEY    = userdata.get('AZURE_OPENAI_KEY')
AZURE_DEPLOYMENT = userdata.get('AZURE_OPENAI_DEPLOYMENT')  # e.g. 'gpt-4o'
AZURE_API_VERSION = '2024-06-01'

# --- HuggingFace Token (for private models / higher rate limits) ---
#HF_TOKEN = userdata.get('HF_TOKEN')  # optional for public models

print('✅ Credentials loaded' if AZURE_API_KEY else '❌ Missing Azure credentials — check Secrets')

SAMPLE_DOCS = [
    {
        "source": "Apple_10K_2023_Risk",
        "text": """RISK FACTORS
Apple's operations and financial results are subject to various risks and uncertainties.
Global and regional economic conditions, including conditions resulting from financial and credit market fluctuations,
can adversely affect demand for Apple's products and services.
Apple faces intense competition in all of its business areas from well-established companies with significant
resources, as well as from new market entrants.
Apple depends on the performance of distributors, carriers, wholesalers and other resellers.
The Company's fiscal year 2023 revenue was
394.3 billion in fiscal 2022,
a decrease of approximately 2.8 percent.
The Company's net income for fiscal 2023 was
6.13 diluted earnings per share,
compared to
6.11 diluted earnings per share, in fiscal 2022.
Apple's gross margin percentage was 44.1% in fiscal 2023, compared to 43.3% in fiscal 2022.
Services revenue reached an all-time high of $85.2 billion in fiscal 2023, up 9 percent year over year."""
    },
    {
        "source": "Apple_10K_2023_Products",
        "text": """PRODUCTS AND SERVICES
Apple designs, manufactures and markets smartphones, personal computers, tablets, wearables and accessories.
iPhone is Apple's line of smartphones based on its iOS operating system.
iPhone net sales were
29.4 billion in fiscal 2023, down from
28.3 billion in fiscal 2023.
Wearables, Home and Accessories net sales were $39.8 billion in fiscal 2023.
Apple's Services segment includes advertising, AppleCare, cloud, digital content, payment and other services.
The App Store, Apple Music, Apple TV+, Apple Arcade, iCloud and Apple Pay are key Services offerings.
The Company had approximately 2.2 billion active devices at the end of fiscal year 2023."""
    },
    {
        "source": "Apple_10K_2023_Liquidity",
        "text": """LIQUIDITY AND CAPITAL RESOURCES
The Company believes its existing balances of cash, cash equivalents and unrestricted marketable securities,
together with cash generated by operations, will be sufficient to satisfy its expected cash needs.
Cash and cash equivalents as of September 30, 2023 were
100.544 billion, consisting of current marketable securities of
100.544 billion.
During fiscal 2023, the Company returned over
15.1 billion in dividends and dividend equivalents and
10.959 billion in fiscal 2023.
The Company's long-term debt as of September 30, 2023 was $95.281 billion."""
    },
]

print(f'📂 Loaded {len(SAMPLE_DOCS)} documents')
for doc in SAMPLE_DOCS:
    print(f'  - {doc["source"]}: {len(doc["text"])} characters')

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document

def create_chunks(docs: list, chunk_size: int = 512, chunk_overlap: int = 64) -> list:
    """Convert raw documents to LangChain Document chunks."""
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=["\n\n", "\n", ". ", " ", ""],
        length_function=len,
    )
    lc_docs = [Document(page_content=d["text"], metadata={"source": d["source"]}) for d in docs]
    chunks = splitter.split_documents(lc_docs)
    return chunks

# Default configuration
CHUNK_SIZE = 512
CHUNK_OVERLAP = 64
chunks = create_chunks(SAMPLE_DOCS, CHUNK_SIZE, CHUNK_OVERLAP)

print(f'✅ Created {len(chunks)} chunks (size={CHUNK_SIZE}, overlap={CHUNK_OVERLAP})')
print('\n📋 Sample chunk:')
print(f'  Source: {chunks[0].metadata["source"]}')
print(f'  Content: {chunks[0].page_content[:200]}...')

import time
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

# Load the embedding model (downloads ~90MB on first run)
print('⏳ Loading HuggingFace embedding model...')
embedding_model = HuggingFaceEmbeddings(
    model_name='sentence-transformers/all-MiniLM-L6-v2',
    model_kwargs={'device': 'cpu'},  # change to 'cuda' if GPU available
    encode_kwargs={'normalize_embeddings': True, 'batch_size': 32}
)

# Build FAISS index
print('⏳ Building FAISS index...')
t0 = time.time()
vectorstore = FAISS.from_documents(chunks, embedding_model)
elapsed = time.time() - t0

print(f'✅ FAISS index built in {elapsed:.2f}s')
print(f'   Vectors: {vectorstore.index.ntotal}')
print(f'   Dimension: {vectorstore.index.d}')

# MMR retriever: fetch_k candidates, return top k diverse results
retriever = vectorstore.as_retriever(
    search_type='mmr',
    search_kwargs={
        'k': 4,          # number of chunks to return
        'fetch_k': 10,   # candidate pool for MMR
        'lambda_mult': 0.7  # 1.0 = pure relevance, 0.0 = pure diversity
    }
)

# Test retrieval
test_query = 'What was Apple revenue in 2023?'
results = retriever.invoke(test_query)
print(f'🔍 Query: "{test_query}"')
print(f'   Retrieved {len(results)} chunks:')
for i, r in enumerate(results):
    print(f'   [{i+1}] {r.metadata["source"]}: {r.page_content[:100]}...')

from langchain_openai import AzureChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

# Initialise Azure OpenAI LLM
llm = AzureChatOpenAI(
    azure_endpoint=AZURE_ENDPOINT,
    azure_deployment=AZURE_DEPLOYMENT,
    openai_api_version=AZURE_API_VERSION,
    openai_api_key=AZURE_API_KEY,
    temperature=0,          # deterministic for financial queries
    max_tokens=512,
    timeout=30,
)

# RAG prompt template — cite sources, be conservative with numbers
RAG_PROMPT = ChatPromptTemplate.from_template("""
You are FinSight, an AI research analyst for a Tier-1 investment bank.
Answer the analyst's question ONLY using the provided context.
If the context does not contain the answer, say: "Insufficient information in the retrieved context."
Always cite the specific source document at the end of your answer.

CONTEXT:
{context}

ANALYST QUESTION: {question}

ANSWER (cite source):
""")

def format_docs(docs):
    return "\n\n".join(
        f"[Source: {d.metadata['source']}]\n{d.page_content}"
        for d in docs
    )

# Build RAG chain
rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | RAG_PROMPT
    | llm
    | StrOutputParser()
)

print('✅ RAG chain built')

from langchain_openai.chat_models import AzureChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

# Initialise Azure OpenAI LLM
llm = AzureChatOpenAI(
    azure_endpoint=AZURE_ENDPOINT,
    azure_deployment=AZURE_DEPLOYMENT,
    openai_api_version=AZURE_API_VERSION,
    openai_api_key=AZURE_API_KEY,
    temperature=0,          # deterministic for financial queries
    max_tokens=512,
    timeout=30,
)

# RAG prompt template — cite sources, be conservative with numbers
RAG_PROMPT = ChatPromptTemplate.from_template("""
You are FinSight, an AI research analyst for a Tier-1 investment bank.
Answer the analyst's question ONLY using the provided context.
If the context does not contain the answer, say: "Insufficient information in the retrieved context."
Always cite the specific source document at the end of your answer.

CONTEXT:
{context}

ANALYST QUESTION: {question}

ANSWER (cite source):
""")

def format_docs(docs):
    return "\n\n".join(
        f"[Source: {d.metadata['source']}]\n{d.page_content}"
        for d in docs
    )

# Build RAG chain
rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | RAG_PROMPT
    | llm
    | StrOutputParser()
)

print('✅ RAG chain built')

import time

TEST_QUERIES = [
    'What was Apple\'s total revenue in fiscal year 2023?',
    'How much cash did Apple have at the end of fiscal 2023?',
    'What percentage of Apple\'s revenue came from iPhone in 2023?',
    'How much did Apple return to shareholders in fiscal 2023?',
    'What is Apple\'s gross margin for fiscal 2023?',
]

results_log = []

for query in TEST_QUERIES:
    t0 = time.time()
    answer = rag_chain.invoke(query)
    latency = time.time() - t0
    results_log.append({'query': query, 'answer': answer, 'latency_s': round(latency, 2)})
    print(f'❓ {query}')
    print(f'   ⏱️  {latency:.2f}s')
    print(f'   💬 {answer[:200]}...')
    print()

!pip install -q --upgrade \
ragas \
langchain \
langchain-core \
langchain-community \
langchain-openai \
google-cloud-aiplatform
!pip install --upgrade google-adk --break-system-packages
! pip install langchain-google-vertexai --break-system-packages
!pip install "opentelemetry-api>=1.36.0,<1.39.0" "opentelemetry-sdk>=1.36.0,<1.39.0" --break-system-packages

# fix old vertex import compatibility
!pip install -q langchain-google-vertexai

print("✅ Fixed RAGAS + LangChain compatibility")

from datasets import Dataset
from ragas import evaluate
from langchain_google_vertexai import ChatVertexAI
from ragas.metrics import faithfulness, answer_relevancy, context_recall, context_precision
from langchain_openai import AzureOpenAIEmbeddings

# Ground truth answers for evaluation
GROUND_TRUTHS = [
    'Apple\'s total revenue in fiscal 2023 was $383.3 billion.',
    'Apple had $29.965 billion in cash and cash equivalents at end of fiscal 2023.',
    'iPhone represented approximately 52% of Apple\'s total revenue in fiscal 2023.',
    'Apple returned over $77 billion to shareholders in fiscal 2023.',
    'Apple\'s gross margin was 44.1% in fiscal 2023.',
]

# Collect contexts used per query
contexts_used = []
for q in TEST_QUERIES:
    docs = retriever.invoke(q)
    contexts_used.append([d.page_content for d in docs])

# Build RAGAS evaluation dataset
eval_dataset = Dataset.from_dict({
    'question':  TEST_QUERIES,
    'answer':    [r['answer'] for r in results_log],
    'contexts':  contexts_used,
    'ground_truth': GROUND_TRUTHS,
})

# Azure OpenAI embeddings for RAGAS
az_embeddings = AzureOpenAIEmbeddings(
    azure_endpoint=AZURE_ENDPOINT,
    azure_deployment='text-embedding-ada-002',  # must be deployed in your Azure resource
    openai_api_key=AZURE_API_KEY,
    openai_api_version=AZURE_API_VERSION,
)

# Run RAGAS evaluation
print('⏳ Running RAGAS evaluation...')
ragas_results = evaluate(
    dataset=eval_dataset,
    metrics=[faithfulness, answer_relevancy, context_recall, context_precision],
    llm=llm,
    embeddings=az_embeddings,
)

print('\n📊 RAGAS Evaluation Results:')
print(ragas_results)

import pandas as pd

# ⚠️ This cell makes multiple API calls — monitor your Azure token budget
CHUNK_SIZES_TO_TEST = [256, 512, 1024]
experiment_results = []

for cs in CHUNK_SIZES_TO_TEST:
    print(f'\n🔧 Testing chunk_size={cs}...')

    # Rebuild index with new chunk size
    exp_chunks = create_chunks(SAMPLE_DOCS, chunk_size=cs, chunk_overlap=cs//8)
    exp_vs = FAISS.from_documents(exp_chunks, embedding_model)
    exp_retriever = exp_vs.as_retriever(search_type='mmr', search_kwargs={'k': 4, 'fetch_k': 10})

    # Build and run chain
    exp_chain = (
        {"context": exp_retriever | format_docs, "question": RunnablePassthrough()}
        | RAG_PROMPT | llm | StrOutputParser()
    )

    answers, latencies = [], []
    for q in TEST_QUERIES[:3]:  # run subset to save cost
        t0 = time.time()
        a = exp_chain.invoke(q)
        latencies.append(time.time() - t0)
        answers.append(a)

    experiment_results.append({
        'chunk_size': cs,
        'n_chunks': len(exp_chunks),
        'avg_latency_s': round(sum(latencies)/len(latencies), 2),
    })
    print(f'   Chunks: {len(exp_chunks)}, Avg latency: {experiment_results[-1]["avg_latency_s"]}s')

df = pd.DataFrame(experiment_results)
print('\n📊 Chunk Size Comparison:')
print(df.to_string(index=False))
print('\n💡 Tip: Run full RAGAS evaluation per chunk_size to see faithfulness trade-offs')