# -*- coding: utf-8 -*-
"""CapstoneTask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H3EHBxO0tbC6PFH3VaXwS_XHcN9ruZd4
"""

!pip install fakeredis chromadb langchain openai tenacity

#Architecture
                """         User
                           |
                           v
                 +------------------+
                 | Input Guardrail  |
                 +------------------+
                           |
                           v
                 +------------------+
                 | Router Agent     |
                 +------------------+
                           |
        ----------------------------------------
        |                  |                  |
        v                  v                  v

+---------------+  +---------------+  +---------------+
| Order Tool    |  | Policy Tool   |  | Ticket Tool   |
| (FastAPI)     |  | (ChromaDB)    |  | Async Queue   |
+---------------+  +---------------+  +---------------+
        |                                    |
        |                                    |
        |                             +-------------+
        |                             | Queue       |
        |                             | Worker      |
        |                             +-------------+
        |
        ---------------------------------
                        |
                        v

               +------------------+
               | Approval Gate    |
               | (Refunds)        |
               +------------------+
                        |
                        v

               +------------------+
               | Output Guardrail |
               +------------------+
                        |
                        v
                      User

------------------------------------------------

Redis      -> Short-term memory
ChromaDB   -> Long-term memory (RAG)
Logging    -> Tracing
Tenacity   -> Retries
Redis      -> Prompt cache
"""

##Redis
import fakeredis
import json

redis_client = fakeredis.FakeStrictRedis()

class Memory:

    def save(self, role, content):

        redis_client.rpush(
            "history",
            json.dumps(
                {
                    "role": role,
                    "content": content
                }
            )
        )

    def load(self):

        return [
            json.loads(x)
            for x in redis_client.lrange(
                "history",
                0,
                -1
            )
        ]

mem = Memory()

mem.save(
    "user",
    "My shipping preference is express"
)

print(mem.load())

#ChromaDB
import chromadb

client = chromadb.Client()

collection = client.create_collection(
    "support_docs",
    get_or_create=True
)

collection.add(
    documents=[
        "Refunds are allowed within 30 days.",
        "Express shipping arrives in 2 days.",
        "Warranty is valid for one year."
    ],
    ids=["1","2","3"]
)
print(
    search_policy(
        "refund policy"
    )
)

def search_policy(query):

    result = collection.query(
        query_texts=[query],
        n_results=1
    )

    return result["documents"][0][0]

#ORDER Tool
ORDERS = {
    "A1001": {
        "status": "shipped",
        "total": 129
    },

    "A1002": {
        "status": "processing",
        "total": 58
    }
}

def get_order(order_id):

    return ORDERS.get(order_id)

import asyncio

ticket_queue = asyncio.Queue()

async def create_ticket(issue):

    await ticket_queue.put(issue)

    return "Ticket queued"

async def worker():

    while True:

        ticket = await ticket_queue.get()

        print(
            "Processing:",
            ticket
        )

        ticket_queue.task_done()

#Router
def router(user_query):

    q = user_query.lower()

    if "order" in q:
        return "order"

    if "refund" in q or "policy" in q:
        return "policy"

    if "ticket" in q:
        return "ticket"

    return "general"

#Chaining
async def handle_damage(order_id):

    order = get_order(order_id)

    result = await create_ticket(
        f"Damage complaint for {order_id}"
    )

    return {
        "order": order,
        "ticket": result
    }

#Human approval Gate
def refund_order(
    order_id,
    approved=False
):

    if not approved:

        return (
            "Approval required"
        )

    return (
        f"Refund issued for {order_id}"
    )
print(
    refund_order(
        "A1001"
    )
)

print(
    refund_order(
        "A1001",
        approved=True
    )
)

#Input Guardrial
BLOCKED = [
    "ignore instructions",
    "reveal customer data"
]

def input_guardrail(text):

    t = text.lower()

    for phrase in BLOCKED:

        if phrase in t:
            return False

    return True

#Output guardrials
import re

def output_guardrail(text):

    return re.sub(
        r"\S+@\S+",
        "[REDACTED]",
        text
    )
print(
    output_guardrail(
        "email me at john@gmail.com"
    )
)



#Retries
from tenacity import retry
from tenacity import stop_after_attempt


@retry(
    stop=stop_after_attempt(3)
)
def flaky_order_lookup(order_id):

    return get_order(order_id)

#Prompt Cache
def cached_answer(question):

    cached = redis_client.get(
        question
    )

    if cached:

        return cached.decode()

    answer = (
        "Generated answer"
    )

    redis_client.set(
        question,
        answer
    )

    return answer

#Logging
import logging

logging.basicConfig(
    level=logging.INFO
)

logger = logging.getLogger(
    "support-agent"
)

#Main Agent
async def agent(query):

    if not input_guardrail(query):

        return "Blocked"

    route = router(query)

    logger.info(
        f"Route={route}"
    )

    if route == "order":

        response = get_order(
            "A1002"
        )

    elif route == "policy":

        response = search_policy(
            query
        )

    elif route == "ticket":

        response = await create_ticket(
            query
        )

    else:

        response = (
            "General support"
        )

    return output_guardrail(
        str(response)
    )

print(
    await agent(
        "What is order A1001 status?"
    )
)