# -*- coding: utf-8 -*-
"""Extension_C_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHEMxZFrJn8ym3yywvSEltgkVazSmglC
"""

#Extension C. Prometheus metrics + Grafana dashboard
!pip install prometheus-client -q
#Create metrices
from prometheus_client import CollectorRegistry, Counter, Histogram, start_http_server # Changed import here

# Create a new registry specifically for these metrics
# This avoids interference with the default global registry and its auto-registered collectors.
registry = CollectorRegistry()

PIPELINE_ROWS = Counter(
    'pipeline_rows_total',
    'Total rows processed',
    registry=registry
)

PIPELINE_ERRORS = Counter(
    'pipeline_errors_total',
    'Total pipeline errors',
    registry=registry
)

VALIDATION_SUCCESS = Counter(
    'validation_success_total',
    'Total successful validations',
    registry=registry
)

VALIDATION_FAILURE = Counter(
    'validation_failure_total',
    'Total failed validations',
    registry=registry
)

STAGE_DURATION_SECONDS = Histogram(
    'stage_duration_seconds',
    'Stage execution time',
    ['stage'],
    registry=registry
)
#Simulate Pipeline
import time

def extract():
    start = time.time()

    rows = 1000
    PIPELINE_ROWS.inc(rows)

    time.sleep(2)

    STAGE_DURATION_SECONDS.labels(
        stage='extract'
    ).observe(time.time() - start)

    return rows


def validate(rows):
    start = time.time()

    valid = 980
    failed = 20

    VALIDATION_SUCCESS.inc(valid)
    VALIDATION_FAILURE.inc(failed)

    STAGE_DURATION_SECONDS.labels(
        stage='validate'
    ).observe(time.time() - start)

    return valid


def load(rows):
    start = time.time()

    time.sleep(1)

    STAGE_DURATION_SECONDS.labels(
        stage='load'
    ).observe(time.time() - start)

try:
    rows = extract()
    valid_rows = validate(rows)
    load(valid_rows)

except Exception:
    PIPELINE_ERRORS.inc()

# Start up the server to expose the metrics.
try:
    start_http_server(8000, registry=registry)
    print("Prometheus metrics server started on port 8000. Access via the provided Colab proxy URL.")
except OSError as e:
    if "Address already in use" in str(e):
        print("Prometheus metrics server is already running on port 8000.")
    else:
        raise

from google.colab.output import eval_js

print(eval_js("google.colab.kernel.proxyPort(8000)"))