# -*- coding: utf-8 -*-
"""Python_pipline_withValidation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s_vVtCsduPH72OohhHs7B6ae2NJ3qm3Y
"""

!pip install pydantic great-expectations pandas apscheduler tenacity loguru rich -q

import importlib, subprocess
for pkg in ["pydantic", "great_expectations", "apscheduler"]:
  print(f"✓ {pkg} {importlib.import_module(pkg).__version__}")

# Cell [2] — Structured logging with Loguru + pipeline config
from loguru import logger
from dataclasses import dataclass, field
from pathlib import Path
import sys

# Remove default handler and configure custom format
logger.remove()
logger.add(
    sys.stdout,
    level="INFO",
    format="{time:HH:mm:ss} | {level: <8} | {message}",
    colorize=True
)
logger.add(
    "pipeline.log",
    rotation="10 MB",
    retention="7 days",
    level="DEBUG"
)


@dataclass
class PipelineConfig:
    """Central configuration for the pipeline. Override fields as needed."""
    source_path: Path = Path("data/raw")
    output_path: Path = Path("data/processed")
    schedule_cron: str = "0 6 * * *"   # 06:00 UTC daily
    max_retries: int = 3
    batch_size: int = 10_000
    alert_email: str = "ops@example.com"
    pass_rate_threshold: float = 0.95   # minimum valid-row ratio
    null_rate_limit: float = 0.05
    min_rows: int = 100


cfg = PipelineConfig()
logger.info(f"Config loaded — schedule: {cfg.schedule_cron} | output: {cfg.output_path}")

import pandas as pd
import numpy as np
from abc import ABC, abstractmethod


class BaseIngestor(ABC):
    """All ingestors return a raw DataFrame. Implement read() for each source."""

    @abstractmethod
    def read(self) -> pd.DataFrame:
        ...


class CsvIngestor(BaseIngestor):
    """Reads a CSV file from disk. Swap for S3/GCS path as needed."""

    def __init__(self, path: str):
        self.path = path

    def read(self) -> pd.DataFrame:
        df = pd.read_csv(self.path)
        logger.info(f"Ingested {len(df):,} rows from {self.path}")
        return df


class SyntheticIngestor(BaseIngestor):
    """Generates synthetic transaction data for demo/testing.
    Deliberately inserts nulls and negative amounts to exercise validation.
    """

    def __init__(self, n: int = 1_000, seed: int = 42):
        self.n = n
        self.seed = seed

    def read(self) -> pd.DataFrame:
        rng = np.random.default_rng(self.seed)
        n = self.n

        amounts = rng.normal(100, 30, n).round(2)
        # Inject ~1% negative amounts to test validation
        neg_idx = rng.choice(n, size=int(n * 0.01), replace=False)
        amounts[neg_idx] = -abs(amounts[neg_idx])

        df = pd.DataFrame({
            "id": range(n),
            "amount": amounts,
            "category": rng.choice(["A", "B", "C", None], n, p=[0.4, 0.3, 0.2, 0.1]),
            "ts": pd.date_range("2024-01-01", periods=n, freq="1h"),
        })

        logger.info(f"Generated {n:,} synthetic rows (seed={self.seed})")
        return df


# ── Run ingestion
raw_df = SyntheticIngestor(n=1_000).read()

print(f"\nShape: {raw_df.shape}")
print(f"Null counts:\n{raw_df.isnull().sum()}")
raw_df.head()

# Cell [4] — Row-level schema validation with Pydantic v2
from pydantic import BaseModel, field_validator, ValidationError
from typing import Optional, Literal
from datetime import datetime


class TransactionRecord(BaseModel):
    """Pydantic model defining the expected schema for each transaction row."""

    id: int
    amount: float
    category: Optional[Literal["A", "B", "C"]]
    ts: datetime

    @field_validator("amount")
    @classmethod
    def amount_positive(cls, v: float) -> float:
        if v <= 0:
            raise ValueError(f"amount must be positive, got {v:.2f}")
        return v

    @field_validator("id")
    @classmethod
    def id_non_negative(cls, v: int) -> int:
        if v < 0:
            raise ValueError(f"id must be non-negative, got {v}")
        return v

def validate_batch(
    df: pd.DataFrame,
    pass_threshold: float = 0.95
) -> tuple[pd.DataFrame, list[dict]]:
    """Validate every row against TransactionRecord.

    Returns:
        valid_df: DataFrame of passing rows
        errors:   list of {row_id, field, message} dicts
    """
    valid_rows, errors = [], []

    for row in df.to_dict("records"):
        try:
            parsed = TransactionRecord(**row)
            valid_rows.append(parsed.model_dump())
        except ValidationError as e:
            for err in e.errors():
                errors.append({
                    "row_id": row.get("id"),
                    "field": err["loc"][0] if err["loc"] else "unknown",
                    "message": err["msg"],
                })

    pass_rate = len(valid_rows) / len(df)
    logger.info(
        f"Validation: {len(valid_rows):,} valid | {len(errors):,} errors | "
        f"{pass_rate*100:.1f}% pass rate"
    )

    if pass_rate < pass_threshold:
        logger.warning(
            f"Pass rate {pass_rate*100:.1f}% is below threshold "
            f"{pass_threshold*100:.0f}% — investigate upstream data"
        )

    valid_df = pd.DataFrame(valid_rows) if valid_rows else pd.DataFrame(columns=df.columns)
    return valid_df, errors


# ── Run validation
valid_df, validation_errors = validate_batch(raw_df, cfg.pass_rate_threshold)

print(f"\nValid rows: {len(valid_df):,}")
print(f"Validation errors: {len(validation_errors)}")
if validation_errors:
    print("\nSample errors:")
    for e in validation_errors[:5]:
        print(f"  row {e['row_id']} | {e['field']}: {e['message']}")

import great_expectations as gx
import pandas as pd


def build_ge_suite(df: pd.DataFrame) -> dict:
    """Run a Great Expectations expectation suite against a DataFrame.

    Returns a results summary dict with passed/evaluated counts.
    """
    context = gx.get_context(mode="ephemeral")

    # Register data source
    ds = context.data_sources.add_pandas("pandas_source")
    da = ds.add_dataframe_asset("transactions")
    batch_def = da.add_batch_definition_whole_dataframe("full_batch")
    batch = batch_def.get_batch(batch_parameters={"dataframe": df})

    # Build expectation suite
    suite = context.suites.add(gx.ExpectationSuite(name="txn_suite"))

    suite.add_expectation(
        gx.expectations.ExpectColumnToExist(column="amount"))
    suite.add_expectation(
        gx.expectations.ExpectColumnToExist(column="id"))
    suite.add_expectation(
        gx.expectations.ExpectColumnValuesToBeBetween(
            column="amount", min_value=0, max_value=300))
    suite.add_expectation(
        gx.expectations.ExpectColumnValuesToNotBeNull(column="id"))
    suite.add_expectation(
        gx.expectations.ExpectColumnValuesToNotBeNull(column="ts"))
    suite.add_expectation(
        gx.expectations.ExpectColumnValuesToBeInSet(
            column="category",
            value_set=["A", "B", "C"],
            mostly=0.90))   # allow up to 10% nulls / unknowns
    suite.add_expectation(
        gx.expectations.ExpectColumnValuesToBeUnique(column="id"))
    # Run validation
    # In Great Expectations 1.x, validate directly on the batch
    results = batch.validate(suite)
    stats = results.statistics

    logger.info(
        f"GE suite: {stats['successful_expectations']}/"
        f"{stats['evaluated_expectations']} expectations passed"
    )

    if not results.success:
        failed = [
            r.expectation_config.type
            for r in results.results
            if not r.success
        ]
        logger.warning(f"Failed expectations: {failed}")

    return {
        "success": results.success,
        "passed": stats["successful_expectations"],
        "evaluated": stats["evaluated_expectations"],
    }


# ── Run GE suite
ge_results = build_ge_suite(valid_df)
print(f"\nGE Suite passed: {ge_results['success']}")
print(f"Expectations: {ge_results['passed']}/{ge_results['evaluated']}")

# Cell [6] — Composable, testable transform functions
from functools import reduce
from typing import Callable

# Type alias for transform functions
TransformFn = Callable[[pd.DataFrame], pd.DataFrame]


def fill_category(df: pd.DataFrame) -> pd.DataFrame:
    """Replace null categories with 'UNKNOWN'."""
    return df.assign(category=df["category"].fillna("UNKNOWN"))


def add_amount_tier(df: pd.DataFrame) -> pd.DataFrame:
    """Bin amount into labelled tiers: low / medium / high / premium."""
    bins = [0, 50, 100, 150, float("inf")]
    labels = ["low", "medium", "high", "premium"]
    return df.assign(
        tier=pd.cut(df["amount"], bins=bins, labels=labels).astype(str)
    )


def extract_date_parts(df: pd.DataFrame) -> pd.DataFrame:
    """Extract date, hour, and day-of-week from the timestamp column."""
    ts = pd.to_datetime(df["ts"])
    return df.assign(
        date=ts.dt.date,
        hour=ts.dt.hour,
        day_of_week=ts.dt.day_name(),
    )


def normalize_amount(df: pd.DataFrame) -> pd.DataFrame:
    """Z-score normalize the amount column."""
    mu, sigma = df["amount"].mean(), df["amount"].std()
    return df.assign(amount_z=((df["amount"] - mu) / sigma).round(4))


def drop_duplicates(df: pd.DataFrame) -> pd.DataFrame:
    """Remove duplicate IDs, keeping the first occurrence."""
    before = len(df)
    df = df.drop_duplicates(subset=["id"], keep="first")
    dropped = before - len(df)
    if dropped:
        logger.warning(f"Dropped {dropped} duplicate rows")
    return df


def apply_transforms(df: pd.DataFrame, *fns: TransformFn) -> pd.DataFrame:
    """Apply a sequence of transform functions left-to-right."""
    return reduce(lambda acc, fn: fn(acc), fns, df)


# ── Run transforms
transformed_df = apply_transforms(
    valid_df,
    drop_duplicates,
    fill_category,
    add_amount_tier,
    extract_date_parts,
    normalize_amount,
)

logger.info(f"Transform complete. Columns: {transformed_df.columns.tolist()}")
print(f"\nFinal shape: {transformed_df.shape}")
print(f"Tier distribution:\n{transformed_df['tier'].value_counts()}")
transformed_df.head()

# Cell [7] — Quality gate with structured checks and alerting hook
from dataclasses import dataclass as dc
from typing import List


@dc
class QualityCheck:
    name: str
    passed: bool
    value: float
    threshold: float
    description: str = ""

    def __str__(self):
        icon = "✓" if self.passed else "✗"
        return (
            f"  {icon} {self.name:<20} "
            f"value={self.value:.4f}  threshold={self.threshold}"
        )


def send_alert(to: str, subject: str, body: str) -> None:
    """Alert dispatcher. Replace with SMTP / Slack / PagerDuty in production."""
    logger.warning(f"ALERT → {to} | {subject} | {body}")
    # Example Slack webhook:
    # import requests
    # requests.post(SLACK_WEBHOOK, json={"text": f"*{subject}*\n{body}"})


def run_quality_gate(df: pd.DataFrame, cfg: PipelineConfig) -> List[QualityCheck]:
    """Run all quality checks. Raises RuntimeError on any failure."""
    checks: List[QualityCheck] = [
        QualityCheck(
            name="null_rate",
            passed=df.isnull().mean().max() < cfg.null_rate_limit,
            value=float(df.isnull().mean().max()),
            threshold=cfg.null_rate_limit,
            description="Max null rate across all columns",
        ),
        QualityCheck(
            name="row_count",
            passed=len(df) >= cfg.min_rows,
            value=float(len(df)),
            threshold=float(cfg.min_rows),
            description="Minimum row count",
        ),
        QualityCheck(
            name="amount_mean",
            passed=80 <= df["amount"].mean() <= 120,
            value=float(df["amount"].mean()),
            threshold=100.0,
            description="Amount mean within expected range [80, 120]",
        ),
        QualityCheck(
            name="dup_id_rate",
            passed=float(df["id"].duplicated().mean()) < 0.01,
            value=float(df["id"].duplicated().mean()),
            threshold=0.01,
            description="Duplicate ID rate below 1%",
        ),
        QualityCheck(
            name="amount_z_range",
            passed=df["amount_z"].abs().max() < 5.0,
            value=float(df["amount_z"].abs().max()),
            threshold=5.0,
            description="No extreme outliers (|z| < 5)",
        ),
    ]

    print("Quality Gate Results:")
    for c in checks:
        level = "info" if c.passed else "error"
        getattr(logger, level)(str(c))

    failures = [c for c in checks if not c.passed]
    if failures:
        names = [f.name for f in failures]
        msg = f"Quality gate FAILED on: {names}"
        logger.error(msg)
        send_alert(
            to=cfg.alert_email,
            subject="Pipeline Quality Gate Failure",
            body=msg,
        )
        raise RuntimeError(msg)

    logger.info("Quality gate PASSED — all checks green")
    return checks


# ── Run quality gate
qc_results = run_quality_gate(transformed_df, cfg)

# Cell [8] — Store validated & transformed data as partitioned Parquet
import os
from datetime import date


def store_parquet(df: pd.DataFrame, cfg: PipelineConfig) -> Path:
    """Write DataFrame to a date-partitioned Parquet file.

    Output path: {output_path}/date={today}/data.parquet
    """
    today = date.today().isoformat()
    partition_dir = cfg.output_path / f"date={today}"
    partition_dir.mkdir(parents=True, exist_ok=True)

    out_path = partition_dir / "data.parquet"
    df.to_parquet(out_path, index=False, compression="snappy")

    size_kb = out_path.stat().st_size / 1024
    logger.info(f"Stored {len(df):,} rows → {out_path} ({size_kb:.1f} KB)")
    return out_path


# ── Store
output_path = store_parquet(transformed_df, cfg)

# Verify round-trip
readback = pd.read_parquet(output_path)
assert len(readback) == len(transformed_df), "Row count mismatch on readback!"
logger.info(f"Round-trip verified: {len(readback):,} rows read back successfully")
print(f"\nOutput: {output_path}")

# Cell [9] — End-to-end pipeline runner with Tenacity retry
from tenacity import (
    retry,
    stop_after_attempt,
    wait_exponential,
    retry_if_exception_type,
    before_sleep_log,
)
import logging

_std_logger = logging.getLogger("pipeline")


@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=4, max=60),
    retry=retry_if_exception_type((IOError, ConnectionError)),
    before_sleep=before_sleep_log(_std_logger, logging.WARNING),
    reraise=True,
)
def run_pipeline(cfg: PipelineConfig) -> dict:
    """Execute the full ETL pipeline end-to-end.

    Stages:
        1. Ingest      — load raw data from source
        2. Validate    — Pydantic row-level schema check
        3. GE suite    — dataset-level expectation checks
        4. Transform   — enrich, normalise, bin
        5. Quality gate— statistical checks, alert on failure
        6. Store       — write partitioned Parquet

    Returns:
        dict with run statistics
    """
    logger.info("=" * 50)
    logger.info("Pipeline run STARTED")
    logger.info("=" * 50)

    try:
        # 1. Ingest
        raw = SyntheticIngestor(n=cfg.batch_size).read()

        # 2. Pydantic validation
        valid, errors = validate_batch(raw, cfg.pass_rate_threshold)

        # 3. Great Expectations suite
        ge = build_ge_suite(valid)
        if not ge["success"]:
            raise RuntimeError("Great Expectations suite failed")

        # 4. Transforms
        processed = apply_transforms(
            valid,
            drop_duplicates,
            fill_category,
            add_amount_tier,
            extract_date_parts,
            normalize_amount,
        )

        # 5. Quality gate
        run_quality_gate(processed, cfg)

        # 6. Store
        out = store_parquet(processed, cfg)

        stats = {
            "status": "success",
            "raw_rows": len(raw),
            "valid_rows": len(valid),
            "validation_errors": len(errors),
            "output_path": str(out),
        }
        logger.info("=" * 50)
        logger.info("Pipeline run SUCCEEDED")
        logger.info(f"Stats: {stats}")
        logger.info("=" * 50)
        return stats

    except Exception as e:
        logger.error(f"Pipeline FAILED: {e}")
        send_alert(cfg.alert_email, "Pipeline Failure", str(e))
        raise


# ── Run pipeline once immediately
run_stats = run_pipeline(cfg)
print(f"\nRun stats: {run_stats}")

#Extension C. Prometheus metrics + Grafana dashboard
!pip install prometheus-client -q
#Create metrices
from prometheus_client import CollectorRegistry, Counter, Histogram, start_http_server # Changed import here

# Create a new registry specifically for these metrics
# This avoids interference with the default global registry and its auto-registered collectors.
registry = CollectorRegistry()

PIPELINE_ROWS = Counter(
    'pipeline_rows_total',
    'Total rows processed',
    registry=registry
)

PIPELINE_ERRORS = Counter(
    'pipeline_errors_total',
    'Total pipeline errors',
    registry=registry
)

VALIDATION_SUCCESS = Counter(
    'validation_success_total',
    'Total successful validations',
    registry=registry
)

VALIDATION_FAILURE = Counter(
    'validation_failure_total',
    'Total failed validations',
    registry=registry
)

STAGE_DURATION_SECONDS = Histogram(
    'stage_duration_seconds',
    'Stage execution time',
    ['stage'],
    registry=registry
)
#Simulate Pipeline
import time

def extract():
    start = time.time()

    rows = 1000
    PIPELINE_ROWS.inc(rows)

    time.sleep(2)

    STAGE_DURATION_SECONDS.labels(
        stage='extract'
    ).observe(time.time() - start)

    return rows


def validate(rows):
    start = time.time()

    valid = 980
    failed = 20

    VALIDATION_SUCCESS.inc(valid)
    VALIDATION_FAILURE.inc(failed)

    STAGE_DURATION_SECONDS.labels(
        stage='validate'
    ).observe(time.time() - start)

    return valid


def load(rows):
    start = time.time()

    time.sleep(1)

    STAGE_DURATION_SECONDS.labels(
        stage='load'
    ).observe(time.time() - start)

try:
    rows = extract()
    valid_rows = validate(rows)
    load(valid_rows)

except Exception:
    PIPELINE_ERRORS.inc()

# Start up the server to expose the metrics.
start_http_server(8000, registry=registry) # Added this line

print("Prometheus metrics server started on port 8000. Access via the provided Colab proxy URL.") # Added confirmation message

from google.colab.output import eval_js

print(eval_js("google.colab.kernel.proxyPort(8000)"))

