# -*- coding: utf-8 -*-
"""Day6_Automation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12we8MZUJsSYbh9rU_UBS03Krt2DCV2ev
"""

import requests
from bs4 import BeautifulSoup

url = "https://example.com"

response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")

title = soup.find("h1")

print(title.text)

import subprocess

result = subprocess.run(
    ["ls"],
    capture_output=True,
    text=True
)

print(result.stdout)

#Argparse
import argparse

parser = argparse.ArgumentParser()

parser.add_argument("data.csv", required=True)

args = parser.parse_args()

print("Processing:", args.file)

import requests
import pandas as pd
from datetime import datetime

url = "https://jsonplaceholder.typicode.com/posts"
response = requests.get(url)
if response.status_code == 200:
    data = response.json()
    df = pd.DataFrame(data)
    filename = f"posts_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"

    df.to_csv(filename, index=False)

    print(f"Data saved to {filename}")

else:
    print("API request failed")

