# -*- coding: utf-8 -*-
"""SmartFAQBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fzKLaXXSKAvHBVe_9RcvHj-iqOvA38jF
"""

!pip install -q langchain langchain-core langchain-community langchain-groq
!pip install -q faiss-cpu sentence-transformers

import os
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_core.documents import Document
from langchain_groq import ChatGroq

# SET YOUR GROQ KEY
os.environ["GROQ_API_KEY"] = "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"

# FAQ DATASET
faqs = [
"Return policy is 7 days refund on unused items",
"Shipping takes 3 to 5 business days in India",
"We accept UPI, cards, and net banking",
"You can delete account via support email request",
"Orders can be tracked using tracking ID",
"Customer support is available 24/7",
"Warranty covers only manufacturing defects",
"Cancel order within 2 hours of placing it",
"Cash on delivery is available in selected cities",
"Login issues can be solved via OTP reset"
]

# EMBEDDINGS (OFFLINE)
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# CREATE VECTOR STORE (FAISS)
db = FAISS.from_documents(
    [Document(page_content=f) for f in faqs],
    embeddings
)

# GROQ LLM
llm = ChatGroq(
    model="llama-3.1-8b-instant",
    api_key=os.environ["GROQ_API_KEY"]
)

print("🚀 Smart FAQ Bot Ready! Type 'exit' to stop\n")

#  CLI LOOP
while True:
    query = input("You: ")

    if query.lower() == "exit":
        print("Goodbye!")
        break

    # RETRIEVE TOP-2
    results = db.similarity_search_with_score(query, k=2)

    context = "\n".join([r[0].page_content for r in results])
    scores = [round(r[1], 3) for r in results]

    # PROMPT FOR GROQ
    prompt = f"""
You are a FAQ assistant.
Answer ONLY using the context below.

Context:
{context}

User Question: {query}

Give a short, clear answer.
"""

    response = llm.invoke(prompt).content

    print("\nBot:", response)
    print("Similarity scores:", scores, "\n")